/*
-- MySQL Script generated by MySQL Workbench
-- Mon Oct  5 18:49:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Author: Rafael Morones Burgos.
-- Version: 1.0.0
-- Since: 05/10/2026
*/
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `port_management_malaga` DEFAULT CHARACTER SET utf8 ;
USE `port_management_malaga`;

-- -----------------------------------------------------
-- Tabla "Usuario": Define los atributos que tienen los
-- usuarios datos de alta en la plataforma.
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `port_management_malaga`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `DNI` VARCHAR(10) NOT NULL,
  `nombre1` VARCHAR(50) NOT NULL,
  `nombre2` VARCHAR(50),
  `apellido2` VARCHAR(50) NOT NULL,
  `apellido1` VARCHAR(50) NOT NULL,
  `correoUsuario` VARCHAR(150) NOT NULL,
  `passwordUsuario` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUsuario`))
  CONSTRAINT 
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tabla `mydb`.`Embarcacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `port_management_malaga`.`Embarcacion` (
  `idEmbarcacion` INT NOT NULL AUTO_INCREMENT,
  `matricula`,
  `titular`
  PRIMARY KEY (`idEmbarcacion`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tabla `mydb`.`Muelle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `port_management_malaga`.`Muelle` (
  `idMuelle` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idMuelle`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tabla `mydb`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `port_management_malaga`.`Servicio` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idServicio`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tabla `mydb`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `port_management_malaga`.`Reservas` (
  `idReservas` INT NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFin` DATETIME NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Embarcacion_idEmbarcacion` INT NOT NULL,
  `Muelle_idMuelle` INT NOT NULL,
  PRIMARY KEY (`idReservas`),
  INDEX `fk_Reservas_Usuario_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Reservas_Embarcacion1_idx` (`Embarcacion_idEmbarcacion` ASC),
  INDEX `fk_Reservas_Muelle1_idx` (`Muelle_idMuelle` ASC),
  CONSTRAINT `fk_Reservas_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservas_Embarcacion1`
    FOREIGN KEY (`Embarcacion_idEmbarcacion`)
    REFERENCES `mydb`.`Embarcacion` (`idEmbarcacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservas_Muelle1`
    FOREIGN KEY (`Muelle_idMuelle`)
    REFERENCES `mydb`.`Muelle` (`idMuelle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tabla `mydb`.`Reservas_has_Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `port_management_malaga`.`Reservas_has_Servicio` (
  `Reservas_idReservas` INT NOT NULL,
  `Servicio_idServicio` INT NOT NULL,
  PRIMARY KEY (`Reservas_idReservas`, `Servicio_idServicio`),
  INDEX `fk_Reservas_has_Servicio_Servicio1_idx` (`Servicio_idServicio` ASC),
  INDEX `fk_Reservas_has_Servicio_Reservas1_idx` (`Reservas_idReservas` ASC),
  CONSTRAINT `fk_Reservas_has_Servicio_Reservas1`
    FOREIGN KEY (`Reservas_idReservas`)
    REFERENCES `mydb`.`Reservas` (`idReservas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservas_has_Servicio_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `mydb`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

